# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kughSK5I4OTm9U2FwHYSwVF2I5t-D2tE
"""

A={1,2,2,3,3,3}
print(A)
print(len(A))
A.remove(2)
print(A)
A.clear()
print(A)

print("União dos conjuntos:")
A = {3,6,5,8,1,7}
B = {2,3,4,5,6,7}
C = A.union(B)
print(C)
C = A | B
print(C)

print("Interseção dos conjuntos:")
A = {3,6,5,8,1,7}
B = {2,3,4,5,6,7}
C = A.intersection(B)
print(C)
C = A & B
print(C)

print("Diferença dos conjuntos:")
A = {3,6,5,8,1,7}
B = {2,3,4,5,6,7}
C = A - B
print(C, "<- (A - B)")
C = B - A
print(C, "<- (B - A)")

A = {3,6,5,8,1,7}
B = {3,5}
if 4 in B:
  print("Sim! Verdadeiro")
else:
  print("Nah, Falso")

print(A <= B)
print(B <= A)
print(B < A)

print("Complemento e um conjunto:")
S = {0,1,2,3,4,5,6,7,8,9}
A = {3,6,5,8,1,7}
A_ = S - A
print(A_)
print(A.union(A_), " e ", S)

print("Números complexos:")
z1 = complex(3,4)
z2 = 1 + 2j
z3 = complex(7,9)
print(z1, z2, z3)
print(z1*z2)
print(z1/z2)